### ISSUE TITLE
使用说明系列（部署中有问题此issue讨论）

### ISSUE THREAD

**Issue by removeif** [removeif/hexo-theme-amazing#16]
### 使用主题前请仔细阅读主题[README.md](https://github.com/removeif/hexo-theme-amazing/blob/master/README.md)，以及主题配置文件[_config.yml](https://github.com/removeif/hexo-theme-amazing/blob/master/_config.yml)!!!

**Comment by removeif** [comment]
1.首页文章折叠方法
适当位置放入标签 `<!-- more -->`此标签之后的部分在首页自动影藏，此标签之前的部分为摘要，会放入文章的description字段中，此部分最好对此文章作总结，以便于于更好的seo。

**Comment by removeif** [comment]
2.首页个人资料，左边一言句子 配置文件中可以关闭，也可以点击句子自动切换一言句子。

**Comment by removeif** [comment]
3.关于加密文章的使用以及缺少依赖包的问题
- 完全使用readme中提供的文件package.json内容替换博客目录下的package.json，**并非主题目录下的package.json！！！**
```json
{
  "name": "hexo-site",
  "version": "3.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "ajv": "^6.10.2",
    "bulma-stylus": "0.8.0",
    "deepmerge": "^4.2.2",
    "hexo": "^4.2.0",
    "hexo-blog-encrypt": "^3.0.3",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-log": "^1.0.0",
    "hexo-pagination": "^1.0.0",
    "hexo-renderer-inferno": "^0.1.1",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-util": "^1.8.0",
    "inferno": "^7.3.3",
    "inferno-create-element": "^7.3.3",
    "js-yaml": "^3.13.1",
    "moment": "^2.22.2",
    "save": "^2.4.0",
    "semver": ">=5.0.0"
  }
}
```
- 删除博客目录下node_modules已有依赖包
- 博客目录下执行 npm install 安装依赖包

**Comment by removeif** [comment]
### 3.关于widget的增减
- 如果要去掉一个widget，只需要在主题配置文件_config.yml中注释 相应的widget，如不需要邮件订阅的widget则注释如下
```yaml
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: tags
    # Google FeedBurner email subscription widget configurations
    #-
        # Where should the widget be placed, left sidebar or right sidebar
        #position: right
        #type: subscribe_email
        # Hint text under the email input
        #description: 输入邮箱开始订阅，更博后邮件通知！
        # Feedburner ID
        #feedburner_id: removeifFeedsId
```
- 注意一定要把该节点的 `-`这个符号一起注释掉，否则会报错
- 节点中` position: right `代表是在左还是在右显示

**Comment by removeif** [comment]
### 5.logo图片设置方法
从网站 https://www.qt86.com/ 设计一张带字透明的图片，放到 主题img中，配置文件中相应logo地方引用此图片就可以了

**Comment by removeif** [comment]
### 6.配置文件注释 主题问题！！！
配置前面有此 `-` 的需要把此 `-` 一起注释掉，否则编译会报错！

**Comment by removeif** [comment]
### 7.gitalk 评论使用
- 配置文件中开启如下配置
```yaml
comment:
    type: gitalk
    owner: removeif         # (required) GitHub user name
    repo: blog_comment          # (required) GitHub repository name
    client_id: 46a9f3481b46ea0129d8     # (required) OAuth application client id
    client_secret: 79c7c9cb847e141757d7864453bcbf89f0655b24 # (required) OAuth application client secret
    admin: ['removeif']
    create_issue_manually: true
    distraction_free_mode: false
    has_hot_recommend: true # 是否有热门推荐
    has_latest_comment: true #是否有最新评论
```
- owner：github 账号名，如URL中 https://github.com/removeif 中的**removeif**
- repo：放评论的仓库，需要自己去GitHub创建一个public类型的仓库
- client_id，client_secret 申请
找到如图位置
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200416105841.png)
新建app
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200416105917.png)
填写完内容，然后点击register xxx 创建完成
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200416110213.png)
找到刚刚创建的app，点击进去找到相关client_id，client_secret参数
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200416110254.png)
- admin 管理员参数，博客文章里第一次点进去需要初始化issue，需要用此账号登录 初始化，可填多个，如  ['removeif','dogzi']，同时配置**create_issue_manually: true**，此时才能点击初始化，自动创建issue
