### ISSUE TITLE
icarus 某些源码没理解，请教一下博主

### ISSUE THREAD

**Issue by JIeJaitt** [removeif/hexo-theme-amazing#85]
关于顶部菜单栏的代码
```yml
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
        Album: /album
        Friend: /friend
        Message: /message
        Self-talking: /self-talking
        Music: /music
        Media: /media
```
我观察所有的这些路径都在`hexo-theme-amazing/ex-pages/source`下面有相应的md文件用来生成并链接到对应的界面，但是
```yml
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
```
这四个在`hexo-theme-amazing/ex-pages/source`路径下是没有对应的md文件的，那么关于archives，categories和tags这三个路由的页面是怎么生成的呢？
